### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the top N populated cities in a continent where N is provided by the user

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#14]

**Comment by piafle3005** [comment]
SELECT city.name, country.continent, country.population
FROM city, country
WHERE city.country = country. name
AND country.continent=’name of continent’;
ORDER BY city.population DESC
LIMIT :N;

public City getUseCase4(String continent, int n)
{
try
{
// Create an SQL statement
Statement stmt = con.createStatement();
// Create string for SQL statement
String strSelect =
“SELECT city.name, country.continen, country.populationt”
       + “FROM city, country”
       + “WHERE city.country = country. name"
       + "AND country.continent=" + continent
       + “ORDER BY city.population DESC”
       + “LIMIT: ” + n;
// Execute SQL statement
ResultSet rset = stmt.executeQuery(strSelect);
// Return new country if valid.
// Check one is returned
if (rset.next())
{
City city = new City();
city.name = rset.getString("name");
city.continent = rset.getString("continent");
city.population = rset.getString("population");
return city;
}
else
return null;
}
catch (Exception e)
{
System.out.println(e.getMessage());
System.out.println("Failed to get country details of a continent");
return null;
}
}

public void displayUseCase4(City city)
{
if (city != null)
{
System.out.println(
         “Name of the country: “ + city.name + " \n"
        + "Continent: " + city. continent + "\n"
        + "Population: " + city. population + "\n";
}
}
