### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the top N populated cities in a country where N is provided by the user

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#18]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT city.*
FROM city JOIN country ON city.CountryCode == country.Code
WHERE country.Name = desired_country
ORDER BY city.Population
LIMIT desired_N

* desired_country and desired_N should be input by the user when this is implemented as a method
