### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the capital cities in a continent organised by largest population to smallest 

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#20]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT country.Name, city.ID, city.Name, city.CountryCode, city.District, city.Population, 
FROM city JOIN country ON city.ID = country.Capital
WHERE country.Continent = desired_continent
GROUP BY country.name
ORDER BY city.Population

* desired_continent should be input by the user when this is implemented as a method
