### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report of the top N populated capital cities in the world where N is provided by the user.

### ISSUE THREAD

**Issue by piafle3005** [piafle3005/group3#21]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT country.Name, city.ID, city.Name, city.CountryCode, city.District, city.Population, 
FROM city JOIN country ON city.ID = country.Capital
GROUP BY country.name
ORDER BY city.Population
LIMIT desired_N

* desired_N should be input by the user when this is implemented as a method
