### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report of the population of people, people living in cities, and people not living in cities in each region.

### ISSUE THREAD

**Issue by piafle3005** [piafle3005/group3#24]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT allpops.Country_Region, allpops.Country_Population, allpops.City_Population, (allpops.Country_Population - allpops.City_Population) AS Non_City_Population
FROM (
	SELECT country.Region AS Country_Region, country.Population AS Country_Population, SUM(city.population) AS City_Population
	FROM country.Region, country JOIN city ON country.Code == city.CountryCode
	GROUP BY Country_Region
	) AS allpops
GROUP BY allpops.Region, allpops.Population
