### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report of the population of people, people living in cities, and people not living in cities in each country.

### ISSUE THREAD

**Issue by piafle3005** [piafle3005/group3#25]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT allpops.Country_Name, allpops.Country_Population, allpops.City_Population, (allpops.Country_Population - allpops.City_Population) AS Non_City_Population
FROM (
	SELECT country.Name AS Country_Name, country.Population AS Country_Population, SUM(city.population) AS City_Population
	FROM country.Region, country JOIN city ON country.Code == city.CountryCode
	GROUP BY Country_Name
	) AS allpops
GROUP BY allpops.Country_Name, allpops.Population
