### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the population of people, people living in cities and people not living in cities in each continent 

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#26]

**Comment by Fabian-Skyner** [comment]
SQL Statement:

SELECT allpops.Country_Continent, allpops.Country_Population, allpops.City_Population, (allpops.Country_Population - allpops.City_Population) AS Non_City_Population
FROM (
	SELECT country.Continent AS Country_Continent, country.Population AS Country_Population, SUM(city.population) AS City_Population
	FROM country.Region, country JOIN city ON country.Code == city.CountryCode
	GROUP BY Country_Continent
	) AS allpops
GROUP BY allpops.Country_Continent, allpops.Population
