### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the top N populated countries in a region where N is provided by the user that I can support country reporting of the organisation.

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#7]

**Comment by piafle3005** [comment]
SELECT country.name, country.region
FROM country
WHERE country.region = ‘name of the region’;
ORDER BY city.population DESC
LIMIT :N;
public Country getUseCase6(String region, int n)
    {
        try
        {
            // Create an SQL statement
            Statement stmt = con.createStatement();
            // Create string for SQL statement
            String strSelect =
“SELECT country.name, country.region”
+ “FROM country”
+ “WHERE country.region =” + region
+ “ORDER BY city.population DESC”
+ “LIMIT: ” + n;
            // Execute SQL statement
            ResultSet rset = stmt.executeQuery(strSelect);
            // Return new country if valid.
            // Check one is returned
            if (rset.next())
            {
                Country country2 = new Country();
                country2.name = rset.getString("name");
                country2.region = rset.getString("region");
                return country2;
            }
            else
                return null;
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
            System.out.println("Failed to get country details of a region");
            return null;
        }
    }
