### ISSUE TITLE
As an employee that is working for an organisation that requires reporting on population information I want to create a report for all the cities in the world organised by largest population to smallest that I can support city reporting of the organisation.

### ISSUE THREAD

**Issue by noemifavilli** [piafle3005/group3#8]

**Comment by piafle3005** [comment]
SELECT city.name, city.population 
FROM city
ORDER BY city.population DESC;


 public City getUseCase7(String city)
    {
        try
        {
            // Create an SQL statement
            Statement stmt = con.createStatement();
            // Create string for SQL statement
            String strSelect =
                 “SELECT city.name, city.population“
                  + “FROM city”
                  + “ORDER BY city.population DESC”; //sort from the largest to the smallest
            // Execute SQL statement
            ResultSet rset = stmt.executeQuery(strSelect);
            // Return new city if valid.
            // Check one is returned
            if (rset.next())
            {
                City city = new City();
                city.name = rset.getInt("name");
                city.population = rset.getString("population");
                return city;
            }
            else
                return null;
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
            System.out.println("Failed to get city details");
            return null;
        }
    }
